import {
  LayoutDashboard,
  Package,
  PackagePlus,
  ListOrdered,
  MapPinned,
  CheckCircle2,
  BarChart3,
  Users,
  Truck,
  MapPin,
  Building2,
  ArrowLeftRight,
  Boxes,
  PackageSearch,
  FileText,
  Send,
  Share2,
  Wallet,
  Undo2,
  User,
  Receipt,
  FilePlus2,
  MessageSquareWarning,
  SquarePen,
  UsersRound,
  UserPlus,
  ClipboardList,
  UserCog,
  Banknote,
  Settings,
  Store,
} from 'lucide-react';
import type { NavItem } from '@/components/AppSidebar';

export const NAV_ADMIN: NavItem[] = [
  { label: 'Accueil', href: '/admin', icon: LayoutDashboard },
  {
    label: 'Colis',
    icon: Package,
    children: [
      { label: 'Nouveau', href: '/admin/colis/nouveau', icon: PackagePlus },
      { label: 'Liste', href: '/admin/commandes', icon: ListOrdered },
      { label: 'Suivi', href: '/admin/colis/suivi', icon: MapPinned },
      { label: 'Confirmation', href: '/admin/colis/confirmation', icon: CheckCircle2 },
    ],
  },
  {
    label: 'Statistique',
    icon: BarChart3,
    children: [
      { label: 'Tout', href: '/admin/statistique/tout', icon: BarChart3 },
      { label: 'Client', href: '/admin/statistique/client', icon: Users },
      { label: 'Livreur', href: '/admin/statistique/livreur', icon: Truck },
      { label: 'Zone', href: '/admin/statistique/zone', icon: MapPin },
      { label: 'Ville', href: '/admin/statistique/ville', icon: Building2 },
      { label: 'Comparer', href: '/admin/statistique/comparer', icon: ArrowLeftRight },
    ],
  },
  {
    label: 'Gestion de stock',
    icon: Boxes,
    children: [
      { label: 'Nouveau colis préparation', href: '/admin/stock/nouveau', icon: PackageSearch },
      { label: 'Bon livraison stock', href: '/admin/stock/bon-livraison', icon: FileText },
      { label: 'Inventory', href: '/admin/stock/inventaire', icon: Boxes },
    ],
  },
  { label: 'Bon de livraison', href: '/admin/bon-livraison', icon: FileText },
  { label: "Bon d'envoi", href: '/admin/bon-envoi', icon: Send },
  { label: 'Bon de distribution', href: '/admin/bon-distribution', icon: Share2 },
  {
    label: 'Bon de paiement',
    icon: Wallet,
    children: [
      { label: 'Pour livreur', href: '/admin/bon-paiement/livreur', icon: Truck },
      { label: 'Pour zone', href: '/admin/bon-paiement/zone', icon: MapPin },
    ],
  },
  {
    label: 'Bon de retour',
    icon: Undo2,
    children: [
      { label: 'Pour livreur', href: '/admin/bon-retour/livreur', icon: Truck },
      { label: 'Pour zone', href: '/admin/bon-retour/zone', icon: MapPin },
      { label: 'Pour client', href: '/admin/bon-retour/client', icon: User },
    ],
  },
  {
    label: 'Facture',
    icon: Receipt,
    children: [
      { label: 'Nouvelle facture', href: '/admin/factures/nouvelle', icon: FilePlus2 },
      { label: 'Toutes les factures', href: '/admin/factures/toutes', icon: Receipt },
    ],
  },
  { label: 'Réclamations', href: '/admin/reclamations', icon: MessageSquareWarning },
  { label: 'Modification des colis', href: '/admin/colis/modification', icon: SquarePen },
  { label: 'Marchands', href: '/admin/marchands', icon: Store },
  {
    label: 'Client',
    icon: UsersRound,
    children: [
      { label: 'Liste clients', href: '/admin/clients/liste', icon: Users },
      { label: 'Nouveau client', href: '/admin/clients/nouveau', icon: UserPlus },
    ],
  },
  { label: 'Demande ramassage', href: '/admin/ramassages', icon: ClipboardList },
  {
    label: 'Utilisateurs',
    icon: UserCog,
    children: [
      { label: 'Liste utilisateurs', href: '/admin/equipe', icon: Users },
      { label: 'Nouveau livreur', href: '/admin/utilisateurs/nouveau-livreur', icon: UserPlus },
    ],
  },
  { label: 'Dépenses', href: '/admin/depenses', icon: Banknote },
  { label: 'Paramètres', href: '/admin/parametres', icon: Settings },
];
